language: node_js

sudo: false

cache: yarn

node_js:
  - '6'

env:
  global:
    - CXX=g++-4.8
    - AUTO_BUILD=true

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
      - g++-4.8

before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash
  - export PATH=$HOME/.yarn/bin:$PATH

install:
  - yarn install --pure-lockfile

script:
  - yarn build

after_success:
  - test $AUTO_BUILD == 'true' && bash deploy.sh
